version: "3.8"
services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://smit:Smit123.@localhost/db_smit
      - PYTHONUNBUFFERED=1
      - APP_ENV=production
      - LOG_LEVEL=info
    depends_on:
      - db
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: smit
      POSTGRES_PASSWORD: Smit123.
      POSTGRES_DB: db_smit
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
